kind: wasmer.io/App.v0
owner: zef-j
name: CPVAL_SWE
package: wasmer/static-web-server@2
cli_args:
  - "--root"
  - "__root/client-demo/web"   # serve your web folder from the Git checkout
  - "--directory-listing"
  - "true"
  - "--host"
  - "::"
  - "--port"
  - "80"
