kind: wasmer.io/App.v0
owner: zef-j                # ← change if different
name: CPVAL_SWE             # ← your app name
package: .                  # ← build package from this repo using wasmer.toml
# No cli_args needed: we use the start command from wasmer.toml
