# wasmer.toml — package the static frontend and run it with static-web-server
# Commit this at the REPO ROOT, then deploy via Dashboard or CLI.

[package]
name = "sitev1-web"
version = "0.1.1"
description = "Sitev1 — static frontend (portal + form) packaged for Wasmer Edge"

# Copy this folder into the package root at build time:
[fs]
public = "client-demo/web"

[dependencies]
"wasmer/static-web-server" = "*"

[commands]
# After packaging, '.' points to the copied public dir.
start = "static-web-server --host 0.0.0.0 --port $PORT --root . --directory-listing true"
